/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/CpBCJBICFnq
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

 import { Comfortaa } from 'next/font/google'
 import { Chivo } from 'next/font/google'

 comfortaa({
 subsets: ['latin'],
 display: 'swap',
 })

 chivo({
 subsets: ['latin'],
 display: 'swap',
 })

 To read more about using these font, please visit the Next.js documentation:
 - App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
 - Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
 **/
import Link from "next/link"

export function Hero() {
    return (
        (<main className="flex flex-col min-h-[100dvh]">
            <section
                className="relative w-full h-[80vh] flex items-center justify-center bg-gradient-to-r from-[#0077b6] to-[#00a8e8]">
                <div className="container px-4 md:px-6 text-center space-y-4">
                    <h1 className="text-4xl md:text-6xl font-bold text-white tracking-tight">Taimoor the GOAT</h1>
                    <p className="text-lg md:text-xl text-gray-200">
                        Mastering Data Engineering, Machine Learning, and Deep Learning
                    </p>
                </div>
                <img
                    alt="Taimoor Jassal"
                    className="absolute inset-0 w-full h-full object-cover opacity-30"
                    height={1080}
                    src="/placeholder.svg"
                    style={{
                        aspectRatio: "1920/1080",
                        objectFit: "cover",
                    }}
                    width={1920}/>
            </section>
            <section className="flex justify-center py-12 md:py-24 lg:py-32">
                <div className="container px-4 md:px-6">
                    <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                        <div className="space-y-4">
                            <CodeIcon className="w-12 h-12 text-[#0077b6]"/>
                            <h3 className="text-2xl font-bold">Data Engineering</h3>
                            <p className="text-gray-500 dark:text-gray-400">
                                Proficient in Python, TensorFlow, and PyTorch for building robust data pipelines and
                                machine learning
                                models.
                            </p>
                        </div>
                        <div className="space-y-4">
                            <BrainIcon className="w-12 h-12 text-[#00a8e8]"/>
                            <h3 className="text-2xl font-bold">Machine Learning</h3>
                            <p className="text-gray-500 dark:text-gray-400">
                                Experienced in developing and deploying advanced machine learning models for various
                                applications.
                            </p>
                        </div>
                        <div className="space-y-4">
                            <CpuIcon className="w-12 h-12 text-[#0077b6]"/>
                            <h3 className="text-2xl font-bold">Deep Learning</h3>
                            <p className="text-gray-500 dark:text-gray-400">
                                Skilled in building and optimizing deep neural networks using cutting-edge techniques.
                            </p>
                        </div>
                    </div>
                </div>
            </section>
            <section className="flex justify-center py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800">
                <div className="container px-4 md:px-6">
                    <div className="grid gap-8 md:grid-cols-2 lg:grid-cols-3">
                        <div className="space-y-4">
                            <LinkIcon className="w-12 h-12 text-[#e34c26]"/>
                            <h3 className="text-2xl font-bold">Web Development</h3>
                            <p className="text-gray-500 dark:text-gray-400">
                                Proficient in HTML, CSS, JavaScript, MySQL, and Django for building modern web
                                applications.
                            </p>
                        </div>
                        <div className="space-y-4">
                            <GraduationCapIcon className="w-12 h-12 text-[#00a8e8]"/>
                            <h3 className="text-2xl font-bold">Education</h3>
                            <p className="text-gray-500 dark:text-gray-400">
                                Graduated from the National University of Science and Technology in Islamabad in 2023.
                            </p>
                        </div>
                        <div className="space-y-4">
                            <BriefcaseIcon className="w-12 h-12 text-[#0077b6]"/>
                            <h3 className="text-2xl font-bold">Work Experience</h3>
                            <p className="text-gray-500 dark:text-gray-400">
                                Currently working as a Data Engineer at Systems Technologies in Lahore.
                            </p>
                        </div>
                    </div>
                </div>
            </section>
            <footer className="flex justify-center bg-gray-900 text-white py-6 md:py-12">
                <div
                    className="container px-4 md:px-6 flex flex-col md:flex-row items-center justify-between">
                    <p className="text-sm">© 2024 Taimoor Jassal</p>
                    <nav className="flex gap-4 md:gap-6 text-sm">
                        <Link className="hover:underline" href="#">
                            Home
                        </Link>
                        <Link className="hover:underline" href="#">
                            About
                        </Link>
                        <Link className="hover:underline" href="#">
                            Projects
                        </Link>
                        <Link className="hover:underline" href="#">
                            Contact
                        </Link>
                    </nav>
                </div>
            </footer>
        </main>)
    );
}

function BrainIcon(props) {
    return (
        (<svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <path
                d="M12 5a3 3 0 1 0-5.997.125 4 4 0 0 0-2.526 5.77 4 4 0 0 0 .556 6.588A4 4 0 1 0 12 18Z"/>
            <path
                d="M12 5a3 3 0 1 1 5.997.125 4 4 0 0 1 2.526 5.77 4 4 0 0 1-.556 6.588A4 4 0 1 1 12 18Z"/>
            <path d="M15 13a4.5 4.5 0 0 1-3-4 4.5 4.5 0 0 1-3 4"/>
            <path d="M17.599 6.5a3 3 0 0 0 .399-1.375"/>
            <path d="M6.003 5.125A3 3 0 0 0 6.401 6.5"/>
            <path d="M3.477 10.896a4 4 0 0 1 .585-.396"/>
            <path d="M19.938 10.5a4 4 0 0 1 .585.396"/>
            <path d="M6 18a4 4 0 0 1-1.967-.516"/>
            <path d="M19.967 17.484A4 4 0 0 1 18 18"/>
        </svg>)
    );
}


function BriefcaseIcon(props) {
    return (
        (<svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/>
            <rect width="20" height="14" x="2" y="6" rx="2"/>
        </svg>)
    );
}


function CodeIcon(props) {
    return (
        (<svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <polyline points="16 18 22 12 16 6"/>
            <polyline points="8 6 2 12 8 18"/>
        </svg>)
    );
}


function CpuIcon(props) {
    return (
        (<svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <rect width="16" height="16" x="4" y="4" rx="2"/>
            <rect width="6" height="6" x="9" y="9" rx="1"/>
            <path d="M15 2v2"/>
            <path d="M15 20v2"/>
            <path d="M2 15h2"/>
            <path d="M2 9h2"/>
            <path d="M20 15h2"/>
            <path d="M20 9h2"/>
            <path d="M9 2v2"/>
            <path d="M9 20v2"/>
        </svg>)
    );
}


function GraduationCapIcon(props) {
    return (
        (<svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <path
                d="M21.42 10.922a1 1 0 0 0-.019-1.838L12.83 5.18a2 2 0 0 0-1.66 0L2.6 9.08a1 1 0 0 0 0 1.832l8.57 3.908a2 2 0 0 0 1.66 0z"/>
            <path d="M22 10v6"/>
            <path d="M6 12.5V16a6 3 0 0 0 12 0v-3.5"/>
        </svg>)
    );
}


function LinkIcon(props) {
    return (
        (<svg
            {...props}
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round">
            <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/>
            <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/>
        </svg>)
    );
}
